package com.rong.persist.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("admin_log", "id", AdminLog.class);
		arp.addMapping("admin_relation_role_resource", "id", AdminRelationRoleResource.class);
		arp.addMapping("admin_resource", "id", AdminResource.class);
		arp.addMapping("admin_role", "id", AdminRole.class);
		arp.addMapping("admin_sys_config", "id", AdminSysConfig.class);
		arp.addMapping("my_pwderror_count", "id", PwderrorCount.class);
		arp.addMapping("my_user", "id", User.class);
		arp.addMapping("my_user_third_party", "id", UserThirdParty.class);
		arp.addMapping("my_usertoken", "id", Usertoken.class);
	}
}

