package com.rong.persist.model;

import com.rong.persist.model.base.BaseAdminSysConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminSysConfig extends BaseAdminSysConfig<AdminSysConfig> {
	public static final AdminSysConfig dao = new AdminSysConfig().dao();
	public static final String TABLE = "admin_sys_config";
}
