package com.rong.persist.model;

import com.rong.persist.model.base.BaseAdminRelationRoleResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRelationRoleResource extends BaseAdminRelationRoleResource<AdminRelationRoleResource> {
	public static final AdminRelationRoleResource dao = new AdminRelationRoleResource().dao();
	public static final String TABLE = "admin_relation_role_resource";
}
