package com.rong.persist.model;

import com.rong.persist.model.base.BaseAdminResource;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminResource extends BaseAdminResource<AdminResource> {
	public static final AdminResource dao = new AdminResource().dao();
	public static final String TABLE = "admin_resource";
}
