package com.rong.persist.model;

import com.rong.persist.model.base.BaseAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Admin extends BaseAdmin<Admin> {
	public static final Admin dao = new Admin().dao();
	public static final String TABLE = "admin";
	public static final String SESSION_KEY = "session_login";
}
