package com.rong.persist.model;

import com.rong.persist.model.base.BaseAdminRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminRole extends BaseAdminRole<AdminRole> {
	public static final AdminRole dao = new AdminRole().dao();
	public static final String TABLE = "admin_role";
}
