package com.rong.persist.model;

import com.rong.persist.model.base.BaseAdminLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminLog extends BaseAdminLog<AdminLog> {
	public static final AdminLog dao = new AdminLog().dao();
	public static final String TABLE = "admin_log";
}
