package com.rong.persist.model;

import com.rong.persist.model.base.BasePwderrorCount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PwderrorCount extends BasePwderrorCount<PwderrorCount> {
	public static final PwderrorCount dao = new PwderrorCount().dao();
	public static final String TABLE = "my_pwderror_count";
}
