package com.rong.persist.model;

import com.rong.persist.model.base.BaseUserThirdParty;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserThirdParty extends BaseUserThirdParty<UserThirdParty> {
	public static final UserThirdParty dao = new UserThirdParty().dao();
}
