package com.rong.persist.model;

import com.rong.persist.model.base.BaseUsertoken;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Usertoken extends BaseUsertoken<Usertoken> {
	public static final Usertoken dao = new Usertoken().dao();
	public static final String TABLE = "my_usertoken";
}
