package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePwderrorCount<M extends BasePwderrorCount<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return getInt("userId");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setGwNumber(java.lang.String gwNumber) {
		set("gwNumber", gwNumber);
	}

	public java.lang.String getGwNumber() {
		return getStr("gwNumber");
	}

	public void setPayPwdErrorCount(java.lang.Integer payPwdErrorCount) {
		set("payPwdErrorCount", payPwdErrorCount);
	}

	public java.lang.Integer getPayPwdErrorCount() {
		return getInt("payPwdErrorCount");
	}

	public void setLoginPwdErrorCount(java.lang.Integer loginPwdErrorCount) {
		set("loginPwdErrorCount", loginPwdErrorCount);
	}

	public java.lang.Integer getLoginPwdErrorCount() {
		return getInt("loginPwdErrorCount");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setUpdateTime(java.util.Date updateTime) {
		set("updateTime", updateTime);
	}

	public java.util.Date getUpdateTime() {
		return get("updateTime");
	}

}
