package com.rong.persist.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setUserNickName(java.lang.String userNickName) {
		set("userNickName", userNickName);
	}

	public java.lang.String getUserNickName() {
		return getStr("userNickName");
	}

	public void setUserHead(java.lang.String userHead) {
		set("userHead", userHead);
	}

	public java.lang.String getUserHead() {
		return getStr("userHead");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setGwNumber(java.lang.String gwNumber) {
		set("gwNumber", gwNumber);
	}

	public java.lang.String getGwNumber() {
		return getStr("gwNumber");
	}

	public void setUserPassword(java.lang.String userPassword) {
		set("userPassword", userPassword);
	}

	public java.lang.String getUserPassword() {
		return getStr("userPassword");
	}

	public void setPayPassword(java.lang.String payPassword) {
		set("payPassword", payPassword);
	}

	public java.lang.String getPayPassword() {
		return getStr("payPassword");
	}

	public void setUserType(java.lang.Integer userType) {
		set("userType", userType);
	}

	public java.lang.Integer getUserType() {
		return getInt("userType");
	}

	public void setRegisterDate(java.util.Date registerDate) {
		set("registerDate", registerDate);
	}

	public java.util.Date getRegisterDate() {
		return get("registerDate");
	}

	public void setCode(java.lang.String code) {
		set("code", code);
	}

	public java.lang.String getCode() {
		return getStr("code");
	}

	public void setReferrals(java.lang.String referrals) {
		set("referrals", referrals);
	}

	public java.lang.String getReferrals() {
		return getStr("referrals");
	}

	public void setSupCode(java.lang.String supCode) {
		set("supCode", supCode);
	}

	public java.lang.String getSupCode() {
		return getStr("supCode");
	}

	public void setUserSex(java.lang.Integer userSex) {
		set("userSex", userSex);
	}

	public java.lang.Integer getUserSex() {
		return getInt("userSex");
	}

	public void setUserState(java.lang.Integer userState) {
		set("userState", userState);
	}

	public java.lang.Integer getUserState() {
		return getInt("userState");
	}

	public void setLongitude(java.lang.Double longitude) {
		set("longitude", longitude);
	}

	public java.lang.Double getLongitude() {
		return getDouble("longitude");
	}

	public void setLatitude(java.lang.Double latitude) {
		set("latitude", latitude);
	}

	public java.lang.Double getLatitude() {
		return getDouble("latitude");
	}

	public void setQqNo(java.lang.String qqNo) {
		set("qqNo", qqNo);
	}

	public java.lang.String getQqNo() {
		return getStr("qqNo");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}

	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public void setLoginType(java.lang.Integer loginType) {
		set("loginType", loginType);
	}

	public java.lang.Integer getLoginType() {
		return getInt("loginType");
	}

	public void setOneButtonStart(java.lang.Boolean oneButtonStart) {
		set("oneButtonStart", oneButtonStart);
	}

	public java.lang.Boolean getOneButtonStart() {
		return get("oneButtonStart");
	}

	public void setAutoOrders(java.lang.Boolean autoOrders) {
		set("autoOrders", autoOrders);
	}

	public java.lang.Boolean getAutoOrders() {
		return get("autoOrders");
	}

	public void setLoginTime(java.util.Date loginTime) {
		set("loginTime", loginTime);
	}

	public java.util.Date getLoginTime() {
		return get("loginTime");
	}

}
